version: '3.8'

services:

# Postgres
  postgres:
    image: postgres:15
    container_name: multex-postgres
    restart: unless-stopped
    env_file:
      - ./docker/env/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Redis
  redis:
    image: redis:7
    container_name: multex-redis
    restart: unless-stopped

# N8N
  n8n:
    image: n8nio/n8n
    container_name: multex-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - ./docker/env/n8n.env
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
      - redis

# API Gateway
  api-gateway:
    build:
      context: ./apps/api-gateway
    container_name: multex-api
    restart: unless-stopped
    env_file:
      - ./docker/env/api.env
    volumes:
      - ./apps/api-gateway:/usr/src/app
    working_dir: /usr/src/app
    command: npm run dev
    ports:
      - "4000:4000"
    depends_on:
      - n8n

# Nginx
  nginx:
    build:
      context: ./docker
      dockerfile: Dockerfiles/nginx.Dockerfile
    container_name: multex-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway
      - n8n

volumes:
  postgres_data:
  n8n_data:
